sections:
  - name: "Data Science"
    instructions: |
      This label represents the discussion of data science.
    label: "llms"
    threshold: 0.6
  - name: "Machine Learning"
    instructions: |
      This label represents the discussion of machine learning models.
    label: "ml"
    threshold: 0.6
  - name: "LLMs"
    instructions: |
      This label represents the discussion of a large language models.
    label: "llms"
    threshold: 0.6
